name: py_env
channels:
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'ecmwf_grib=1.19.0=1'
- !!python/unicode
  'jasper=1.900.1=4'
- !!python/unicode
  'libpng=1.6.28=0'
- !!python/unicode
  'pygrib=2.0.2=py27_1'
- !!python/unicode
  'pyproj=1.9.5.1=py27_0'
- !!python/unicode
  'alabaster=0.7.10=py27_0'
- !!python/unicode
  'astroid=1.4.9=py27_0'
- !!python/unicode
  'babel=2.4.0=py27_0'
- !!python/unicode
  'backports=1.0=py27_0'
- !!python/unicode
  'backports_abc=0.5=py27_0'
- !!python/unicode
  'basemap=1.0.7=np111py27_0'
- !!python/unicode
  'bleach=1.5.0=py27_0'
- !!python/unicode
  'cairo=1.14.8=0'
- !!python/unicode
  'chardet=2.3.0=py27_0'
- !!python/unicode
  'configparser=3.5.0=py27_0'
- !!python/unicode
  'curl=7.49.0=1'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'decorator=4.0.11=py27_0'
- !!python/unicode
  'docutils=0.13.1=py27_0'
- !!python/unicode
  'entrypoints=0.2.2=py27_1'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'fontconfig=2.12.1=3'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'geos=3.4.2=0'
- !!python/unicode
  'get_terminal_size=1.0.0=py27_0'
- !!python/unicode
  'gitdb2=2.0.0=py27_0'
- !!python/unicode
  'gitpython=2.1.1=py27_0'
- !!python/unicode
  'glib=2.50.2=1'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'hdf4=4.2.11=0'
- !!python/unicode
  'hdf5=1.8.17=1'
- !!python/unicode
  'html5lib=0.999=py27_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'imagesize=0.7.1=py27_0'
- !!python/unicode
  'ipykernel=4.5.2=py27_0'
- !!python/unicode
  'ipython=5.3.0=py27_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py27_0'
- !!python/unicode
  'ipywidgets=6.0.0=py27_0'
- !!python/unicode
  'isort=4.2.5=py27_0'
- !!python/unicode
  'jbig=2.1=0'
- !!python/unicode
  'jedi=0.9.0=py27_1'
- !!python/unicode
  'jinja2=2.9.5=py27_0'
- !!python/unicode
  'joblib=0.11=py27_0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'jsonschema=2.5.1=py27_0'
- !!python/unicode
  'jupyter=1.0.0=py27_3'
- !!python/unicode
  'jupyter_client=5.0.0=py27_0'
- !!python/unicode
  'jupyter_console=5.1.0=py27_0'
- !!python/unicode
  'jupyter_core=4.3.0=py27_0'
- !!python/unicode
  'lazy-object-proxy=1.2.2=py27_0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libnetcdf=4.4.1=0'
- !!python/unicode
  'libsodium=1.0.10=0'
- !!python/unicode
  'libtiff=4.0.6=3'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'libxml2=2.9.4=0'
- !!python/unicode
  'line_profiler=2.0=py27_0'
- !!python/unicode
  'markupsafe=0.23=py27_2'
- !!python/unicode
  'matplotlib=2.0.0=np111py27_0'
- !!python/unicode
  'mistune=0.7.4=py27_0'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'nbconvert=5.1.1=py27_0'
- !!python/unicode
  'nbformat=4.3.0=py27_0'
- !!python/unicode
  'netcdf4=1.2.4=np111py27_0'
- !!python/unicode
  'networkx=1.11=py27_0'
- !!python/unicode
  'notebook=5.0.0=py27_0'
- !!python/unicode
  'numpy=1.11.3=py27_0'
- !!python/unicode
  'numpydoc=0.6.0=py27_0'
- !!python/unicode
  'olefile=0.44=py27_0'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pandocfilters=1.4.1=py27_0'
- !!python/unicode
  'path.py=10.1=py27_0'
- !!python/unicode
  'pathlib2=2.2.0=py27_0'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pep8=1.7.0=py27_0'
- !!python/unicode
  'pexpect=4.2.1=py27_0'
- !!python/unicode
  'pickleshare=0.7.4=py27_0'
- !!python/unicode
  'pillow=4.1.0=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pixman=0.34.0=0'
- !!python/unicode
  'prompt_toolkit=1.0.13=py27_0'
- !!python/unicode
  'psutil=5.2.1=py27_0'
- !!python/unicode
  'ptyprocess=0.5.1=py27_0'
- !!python/unicode
  'pycairo=1.10.0=py27_0'
- !!python/unicode
  'pyflakes=1.5.0=py27_0'
- !!python/unicode
  'pygments=2.2.0=py27_0'
- !!python/unicode
  'pylint=1.6.4=py27_1'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_2'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2017.2=py27_0'
- !!python/unicode
  'pywavelets=0.5.2=np111py27_0'
- !!python/unicode
  'pyyaml=3.12=py27_0'
- !!python/unicode
  'pyzmq=16.0.2=py27_0'
- !!python/unicode
  'qt=5.6.2=3'
- !!python/unicode
  'qtawesome=0.4.4=py27_0'
- !!python/unicode
  'qtconsole=4.2.1=py27_1'
- !!python/unicode
  'qtpy=1.2.1=py27_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.13.0=py27_0'
- !!python/unicode
  'rope=0.9.4=py27_1'
- !!python/unicode
  'scandir=1.5=py27_0'
- !!python/unicode
  'scikit-image=0.13.0=np111py27_0'
- !!python/unicode
  'scipy=0.19.0=np111py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'simplegeneric=0.8.1=py27_1'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'smmap2=2.0.1=py27_0'
- !!python/unicode
  'snowballstemmer=1.2.1=py27_0'
- !!python/unicode
  'sphinx=1.5.1=py27_0'
- !!python/unicode
  'spyder=3.1.3=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'ssl_match_hostname=3.4.0.2=py27_1'
- !!python/unicode
  'subprocess32=3.2.7=py27_0'
- !!python/unicode
  'terminado=0.6=py27_0'
- !!python/unicode
  'testpath=0.3=py27_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'tornado=4.4.2=py27_0'
- !!python/unicode
  'traitlets=4.3.2=py27_0'
- !!python/unicode
  'wcwidth=0.1.7=py27_0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'widgetsnbextension=2.0.0=py27_0'
- !!python/unicode
  'wrapt=1.10.8=py27_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zeromq=4.1.5=0'
- !!python/unicode
  'zlib=1.2.8=3'
prefix: !!python/unicode '/home/s/S.Rasp/anaconda2/envs/py_env'

